---
- name: Create the Ansible user
  ansible.builtin.user:
    name: "ansible"
    state: present
    shell: /bin/bash
    create_home: true
    groups: sudo  # Add to sudo group

- name: Fetch public keys from GitHub
  ansible.builtin.uri:
    url: "https://github.com/{{ github_username }}.keys"
    return_content: true
  register: github_keys

- name: Create .ssh directory for the Ansible user if it doesn't exist
  ansible.builtin.file:
    path: "/home/ansible/.ssh"
    state: directory
    mode: '0700'
    owner: "ansible"
    group: "ansible"

- name: Add GitHub public keys to authorized_keys for the Ansible user
  ansible.builtin.copy:
    content: "{{ github_keys.content }}"
    dest: "/home/ansible/.ssh/authorized_keys"
    owner: "ansible"
    group: "ansible"
    mode: '0600'

- name: Ensure the ansible user can use sudo without password (optional)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'  # Validate the sudoers file syntax
