---
- name: Setup APT Repository and Install sudo
  hosts: proxmox_initial  # This should be your initial host group
  become: true
  vars_files:
    - ../group_vars/proxmox.yml  # This should contain your GitHub username variable

  tasks:
    - name: Add No Subscription Repository
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        filename: pve-no-subscription
        state: present

    - name: Ensure enterprise repo file is not present
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Ensure sudo is installed
      ansible.builtin.apt:
        name: sudo
        state: present
