---
- name: Setup Proxmox with root user
  hosts: proxmox_root
  become: true
  vars_files:
    - ../group_vars/proxmox.yml

  tasks:
    - name: Setup APT repositories and update
      ansible.builtin.include_tasks: ../tasks/setup-apt.yml

    - name: Setup ansible user
      ansible.builtin.include_tasks: ../tasks/setup-ansible-user.yml
